'use strict';
const $=id=>document.getElementById(id);
const COLORS={I:'#69cebe',O:'#d5c461',T:'#b573c5',S:'#a7d65c',Z:'#d56b76',J:'#797acb',L:'#d29a69',X:'#7e9395'};
const worker=new Worker('worker.js');let requestId=0,mode='demo',state,result=null,selected=0,busy=false,auto=false,animating=false,autoTimer=null,version=0;
let stream=null,frameTimer=null,sourceImage=null,rect=null,calibrating=false,drag=null,pausedVision=false,lastFingerprint='',captureWidth=0,captureHeight=0;
const rawCanvas=document.createElement('canvas'),raw=rawCanvas.getContext('2d',{willReadFrequently:true});
function bag(){const a=Object.keys(Tetris.BASE);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function fillQueue(){while(state.queue.length<7)state.queue.push(...bag());}
function demoState(){const board=Tetris.empty();const heights=[3,4,4,3,2,2,1,1,0,0];for(let x=0;x<10;x++)for(let y=20-heights[x];y<20;y++)board[y][x]='X';return {board,piece:'T',queue:['I','S','L','O','J','Z',...bag()],hold:null,start:Tetris.spawn('T'),pieces:0,lines:0};}
function stopAuto(){auto=false;clearTimeout(autoTimer);$('autoplay').textContent='▶ Run sandbox';}
function setStatus(t){$('status').textContent=t;}
function reset(){stopAuto();version++;animating=false;state=demoState();result=null;selected=0;render();analyze();}
function analyze(){if(!state||!state.piece)return;busy=true;result=null;setStatus('Searching...');drawBoard($('forecastCanvas'),Tetris.empty());$('forecastText').textContent='Searching...';$('step').disabled=true;$('candidates').innerHTML='<p class="hint">Searching reachable placements...</p>';$('reason').textContent='Checking reachable routes.';$('route').replaceChildren();worker.postMessage({id:++requestId,state:{...state,depth:mode==='live'?1:+$('depth').value,allowHold:mode==='demo'}});render();}
worker.onmessage=e=>{const d=e.data;if(d.id!==requestId)return;busy=false;if(d.error){setStatus('Search error');$('reason').textContent=d.error;stopAuto();return;}result=d;selected=0;$('timing').textContent=`${d.total} placements / ${Math.round(d.ms)} ms`;
 if(!d.candidates.length){setStatus('No reachable moves');$('candidates').innerHTML='<p class="hint">No room. Reset or check the detected field.</p>';$('reason').textContent='No reachable placement below the ceiling.';stopAuto();render();return;}
 setStatus(mode==='demo'?'Ready':pausedVision?'Frame frozen':'Current frame');renderCandidates();render();if(auto&&mode==='demo')autoTimer=setTimeout(execute,650);
};
function chosen(){return result?.candidates[selected];}
function renderCandidates(){const wrap=$('candidates');wrap.replaceChildren();result.candidates.forEach((c,i)=>{const b=document.createElement('button');b.className='candidate'+(i===selected?' active':'');b.setAttribute('aria-pressed',String(i===selected));const col=Math.min(...Tetris.SHAPES[c.piece][c.pos.r].map(([x])=>x+c.pos.x))+1;b.innerHTML=`<span class="rank">0${i+1}</span><div><div class="title">${c.useHold?'HOLD → ':''}${c.piece} · col ${col}${i===0?' / best':''}</div><div class="desc">Lines +${c.lines} &nbsp; / &nbsp; holes ${c.metrics.holes} &nbsp; / &nbsp; height ${c.metrics.height}</div></div><div class="value">${c.value.toFixed(1)}<small>score</small></div>`;b.onclick=()=>{if(animating)return;selected=i;renderCandidates();render();};wrap.append(b);});$('horizon').max=String(chosen().future.length);$('horizon').value='0';details();}
function details(){const c=chosen();if(!c)return;const diff=c.metrics.holes-result.before.holes;const notes=[];if(c.useHold)notes.push(`Use ${c.piece} from ${state.hold?'HOLD':'NEXT'}, reserve ${state.piece} for later.`);if(c.lines)notes.push(`Clear ${c.lines} ${c.lines===1?'line':'lines'}.`);notes.push(diff>0?`Add ${diff} covered holes.`:diff<0?`Remove covered holes: ${-diff}.`:'No new covered holes.');notes.push(`Height ${c.metrics.height}; lookahead ${c.lookahead} ${c.lookahead===1?'piece':'pieces'}.`);$('reason').textContent=notes.join(' ');
 const path=c.path.slice();while(path.at(-1)==='D')path.pop();const grouped=[];for(const a of path){if(grouped.at(-1)?.a===a)grouped.at(-1).n++;else grouped.push({a,n:1});}const symbols={L:'←',R:'→',D:'↓',CW:'↻',CCW:'↺'};$('route').replaceChildren();if(c.useHold){const s=document.createElement('span');s.textContent='HOLD';$('route').append(s);}for(const g of grouped){const s=document.createElement('span');s.textContent=symbols[g.a]+(g.n>1?' × '+g.n:'');$('route').append(s);}const drop=document.createElement('span');drop.textContent='DROP';$('route').append(drop);forecast();}
function drawCell(ctx,x,y,size,color,alpha=1,outline=false){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.strokeStyle=color;if(outline){ctx.fillStyle=color+'18';ctx.fillRect(x*size+2,y*size+2,size-4,size-4);ctx.lineWidth=2;ctx.strokeRect(x*size+2,y*size+2,size-4,size-4);}else{ctx.fillRect(x*size+1.5,y*size+1.5,size-3,size-3);ctx.fillStyle='#ffffff20';ctx.fillRect(x*size+3,y*size+3,size-6,2);}ctx.restore();}
function drawBoard(canvas,board,{active=null,candidate=null,holes=false,path=false}={}){const ctx=canvas.getContext('2d'),s=canvas.width/10;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#101416';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#242b2e';ctx.lineWidth=.65;for(let x=0;x<=10;x++){ctx.beginPath();ctx.moveTo(x*s,0);ctx.lineTo(x*s,20*s);ctx.stroke();}for(let y=0;y<=20;y++){ctx.beginPath();ctx.moveTo(0,y*s);ctx.lineTo(10*s,y*s);ctx.stroke();}board.forEach((r,y)=>r.forEach((v,x)=>{if(v)drawCell(ctx,x,y,s,COLORS[v]||COLORS.X,.84);}));
 if(holes)for(const [x,y] of Tetris.metrics(board).holeCells){ctx.fillStyle='#f0817e22';ctx.fillRect(x*s+2,y*s+2,s-4,s-4);ctx.strokeStyle='#f0817e88';ctx.beginPath();ctx.moveTo((x+.4)*s,(y+.4)*s);ctx.lineTo((x+.6)*s,(y+.6)*s);ctx.moveTo((x+.6)*s,(y+.4)*s);ctx.lineTo((x+.4)*s,(y+.6)*s);ctx.stroke();}
 if(candidate){if(path){let p=candidate.useHold?Tetris.spawn(candidate.piece):state.start;ctx.strokeStyle='#72e6d066';ctx.setLineDash([3,5]);ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo((p.x+1.5)*s,(p.y+1.5)*s);for(const a of candidate.path){p=Tetris.move(board,candidate.piece,p,a)||p;ctx.lineTo((p.x+1.5)*s,(p.y+1.5)*s);}ctx.stroke();ctx.setLineDash([]);}for(const [dx,dy] of Tetris.SHAPES[candidate.piece][candidate.pos.r])drawCell(ctx,candidate.pos.x+dx,candidate.pos.y+dy,s,'#72e6d0',1,true);}
 if(active)for(const [dx,dy] of Tetris.SHAPES[active.piece][active.pos.r])drawCell(ctx,active.pos.x+dx,active.pos.y+dy,s,COLORS[active.piece]);
}
function drawMini(canvas,types){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);types.forEach((t,i)=>{if(!t)return;const cells=Tetris.SHAPES[t][0],minX=Math.min(...cells.map(c=>c[0])),minY=Math.min(...cells.map(c=>c[1])),maxX=Math.max(...cells.map(c=>c[0]));ctx.save();ctx.translate((100-(maxX-minX+1)*20)/2,i*66+8);for(const [x,y] of cells)drawCell(ctx,x-minX,y-minY,20,COLORS[t]);ctx.restore();});}
function render(){if(!state)return;drawBoard($('board'),state.board,{active:state.piece?{piece:state.piece,pos:state.start}:null,candidate:chosen(),holes:$('showHoles').checked,path:$('showPath').checked});drawMini($('holdCanvas'),[state.hold]);drawMini($('nextCanvas'),state.queue.slice(0,5));$('pieces').textContent=state.pieces;$('lines').textContent=state.lines;$('step').disabled=mode!=='demo'||busy||animating||!chosen();$('autoplay').disabled=mode!=='demo';$('reset').disabled=mode!=='demo';if(chosen())forecast();}
function forecast(){const c=chosen();if(!c)return;const at=Math.min(+$('horizon').value,c.future.length),b=at?c.future[at-1].board:c.board,m=Tetris.metrics(b);$('horizonValue').textContent=at+1;drawBoard($('forecastCanvas'),b,{holes:$('showHoles').checked});$('forecastText').innerHTML=`After <b>${at+1}</b> ${at===0?'piece':'pieces'}<br>Height <b>${m.height}</b><br>Holes <b>${m.holes}</b><br>Bumpiness <b>${m.bump}</b>`;}
async function execute(){const c=chosen();if(mode!=='demo'||busy||animating||!c)return;animating=true;const currentVersion=version;render();setStatus('Following route...');let p=c.useHold?Tetris.spawn(c.piece):{...state.start};const wait=ms=>new Promise(r=>setTimeout(r,ms));for(const a of c.path){if(currentVersion!==version)return;p=Tetris.move(state.board,c.piece,p,a);if(!p){animating=false;stopAuto();setStatus('Route interrupted');return;}drawBoard($('board'),state.board,{active:{piece:c.piece,pos:p},candidate:c,holes:$('showHoles').checked});await wait(auto?15:30);}if(currentVersion!==version)return;await wait(100);if(currentVersion!==version)return;state.board=Tetris.clone(c.board);state.hold=c.newHold;state.queue=c.nextQueue.slice();fillQueue();state.piece=state.queue.shift();state.start=Tetris.spawn(state.piece);state.pieces++;state.lines+=c.lines;animating=false;analyze();}
function stopCapture(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;clearInterval(frameTimer);frameTimer=null;$('sourceVideo').srcObject=null;}
async function switchMode(next){stopAuto();version++;requestId++;busy=false;animating=false;result=null;mode=next;pausedVision=false;lastFingerprint='';stopCapture();sourceImage=null;rect=null;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));$('capturePanel').hidden=mode==='demo';$('visionDetails').hidden=mode==='demo';$('share').hidden=mode!=='live';$('boardLabel').textContent=mode==='demo'?'SANDBOX / 10 × 20':mode==='reference'?'IMAGE / DETECTED FIELD':'CAPTURE / DETECTED FIELD';if(mode==='demo'){reset();return;}state={board:Tetris.empty(),piece:null,queue:[],hold:null,start:null,pieces:0,lines:0};$('candidates').replaceChildren();$('reason').textContent='Waiting for a field image.';$('route').replaceChildren();drawBoard($('forecastCanvas'),Tetris.empty());render();setStatus('Waiting for frame');const ctx=$('sourceCanvas').getContext('2d');ctx.clearRect(0,0,$('sourceCanvas').width,$('sourceCanvas').height);if(mode==='reference'){const img=new Image();img.onload=()=>{if(mode!=='reference')return;sourceImage=img;captureFrame(true);};img.src='assets/sample-board.png';}else $('captureStatus').textContent='Capture not started.';}
function paintSource(){const canvas=$('sourceCanvas');canvas.width=rawCanvas.width;canvas.height=rawCanvas.height;const ctx=canvas.getContext('2d');ctx.drawImage(rawCanvas,0,0);if(rect){ctx.strokeStyle='#72e6d0';ctx.lineWidth=Math.max(2,canvas.width/600);ctx.strokeRect(rect.x,rect.y,rect.w,rect.h);ctx.fillStyle='#72e6d0';ctx.font=`${Math.max(14,canvas.width/90)}px Segoe UI`;ctx.fillText('10 × 20',rect.x+8,Math.max(20,rect.y-10));}}
function captureFrame(force=false){if(calibrating||pausedVision&&!force||busy&&!force)return;const src=sourceImage||$('sourceVideo'),w=src.naturalWidth||src.videoWidth,h=src.naturalHeight||src.videoHeight;if(!w||!h)return;if(captureWidth!==w||captureHeight!==h){rect=null;captureWidth=w;captureHeight=h;}rawCanvas.width=w;rawCanvas.height=h;raw.drawImage(src,0,0,w,h);const image=raw.getImageData(0,0,w,h);if(!rect)rect=Vision.detect(image);paintSource();if(!rect){$('captureStatus').textContent='No grid found. Use Select grid.';return;}readFrame(image,force);}
function readFrame(image,force=false){const v=Vision.read(image,rect),key=JSON.stringify([v.board,v.active,v.queue,v.hold]);$('captureStatus').textContent=`Field ${Math.round(rect.w)} × ${Math.round(rect.h)} px · ${stream?'live':'image'}`;$('visionText').textContent=`Colored cells: ${v.occupied}. Ambiguous: ${v.ambiguous}. ${v.active?'Active: '+v.active.piece+'.':'Active piece unclear; check the field.'} HOLD: ${v.hold||'—'}. NEXT: ${v.queue.join(' ')||'unknown'}.`;
 if(key===lastFingerprint&&!force)return;lastFingerprint=key;state={board:v.board,piece:v.active?.piece||null,start:v.active?.start||null,queue:v.queue,hold:v.hold,pieces:0,lines:0};result=null;render();if(v.active){$('pieceOverride').value=v.active.piece;$('queueOverride').value=v.queue.join('');analyze();}else{requestId++;busy=false;$('candidates').replaceChildren();$('reason').textContent='Edit cells, choose the active piece and recalculate from spawn.';setStatus('Check field');}}
function sourcePoint(e){const r=$('sourceCanvas').getBoundingClientRect();return {x:(e.clientX-r.left)*rawCanvas.width/r.width,y:(e.clientY-r.top)*rawCanvas.height/r.height};}
$('sourceCanvas').onpointerdown=e=>{if(!calibrating||!rawCanvas.width)return;drag=sourcePoint(e);$('sourceCanvas').setPointerCapture(e.pointerId);};
$('sourceCanvas').onpointermove=e=>{if(!drag)return;const p=sourcePoint(e);rect={x:Math.min(drag.x,p.x),y:Math.min(drag.y,p.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y)};paintSource();};
$('sourceCanvas').onpointerup=e=>{if(!drag)return;drag=null;calibrating=false;$('sourceCanvas').style.cursor='default';if(rect.w<30||rect.h<60){rect=null;$('captureStatus').textContent='Selection too small.';return;}pausedVision=false;lastFingerprint='';readFrame(raw.getImageData(0,0,rawCanvas.width,rawCanvas.height),true);};
$('share').onclick=async()=>{try{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Capture unavailable. Open in Chrome or Edge.');const next=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:60,max:60}},audio:false});stopCapture();sourceImage=null;stream=next;rect=null;pausedVision=false;$('sourceVideo').srcObject=stream;await $('sourceVideo').play();stream.getVideoTracks()[0].onended=()=>{stopCapture();setStatus('Capture stopped');$('captureStatus').textContent='Capture stopped. Last frame retained.';};captureFrame(true);frameTimer=setInterval(()=>captureFrame(),33);}catch(e){$('captureStatus').textContent=e.name==='NotAllowedError'?'Source selection canceled.':e.message;}};
$('upload').onchange=e=>{const file=e.target.files[0];if(!file)return;stopCapture();const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{sourceImage=img;rect=null;pausedVision=false;captureFrame(true);URL.revokeObjectURL(url);};img.onerror=()=>{$('captureStatus').textContent='Could not open image.';URL.revokeObjectURL(url);};img.src=url;};
$('detect').onclick=()=>{rect=null;pausedVision=false;captureFrame(true);};
$('calibrate').onclick=()=>{if(!rawCanvas.width||!sourceImage&&!stream){$('captureStatus').textContent='Choose a source first.';return;}calibrating=true;pausedVision=true;$('sourceCanvas').style.cursor='crosshair';$('captureStatus').textContent='Drag from the top-left to the bottom-right of the inner grid.';};
$('board').onclick=e=>{if(mode==='demo')return;const r=$('board').getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*10),y=Math.floor((e.clientY-r.top)/r.height*20);if(x<0||x>9||y<0||y>19)return;pausedVision=true;state.board[y][x]=state.board[y][x]?null:'X';result=null;render();if(state.piece)analyze();};
$('applyOverride').onclick=()=>{pausedVision=true;state.piece=$('pieceOverride').value;state.start=Tetris.spawn(state.piece);state.queue=$('queueOverride').value.toUpperCase().split('').filter(t=>Tetris.BASE[t]);analyze();};
$('copyToDemo').onclick=async()=>{if(!state.piece){$('visionText').textContent='Choose an active piece and Recalculate.';return;}const saved={...state,board:Tetris.clone(state.board),queue:state.queue.slice()};await switchMode('demo');state=saved;fillQueue();analyze();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
$('autoplay').onclick=()=>{if(auto){stopAuto();setStatus('Sandbox paused');}else{auto=true;$('autoplay').textContent='Ⅱ Pause';if(!busy&&!animating)execute();}};
$('step').onclick=()=>{stopAuto();execute();};$('reset').onclick=reset;
$('depth').onchange=()=>{if(animating){return;}analyze();};$('horizon').oninput=forecast;$('showHoles').onchange=render;$('showPath').onchange=render;
document.addEventListener('keydown',e=>{if(e.code==='Escape'){stopAuto();}});
$('launchOverlay').onclick=async()=>{const b=$('launchOverlay');b.disabled=true;try{const response=await fetch('/launch-overlay',{method:'POST',headers:{'Content-Type':'application/json','X-Tetris-Lab':'launch-overlay'},body:'{}'});if(!response.ok)throw new Error('Launch failed. Open OVERLAY.cmd from the app folder.');$('overlayLaunchStatus').textContent='Scifica launched. Use Select field in its panel.';}catch(e){$('overlayLaunchStatus').textContent=e.message;}finally{b.disabled=false;}};
reset();
